use BASEDEDADOS

select C.PRIMEIRO_NOME, C.SOBRENOME, EC.ESTADO, EC.CIDADE, EC.RUA, TC.NUMERO, TC.TIPO from CLIENTES C
inner join ENDERECO_CLIENTES EC on EC.ID_CLIENTE = C.IDCLIENTE
inner join TELEFONE_CLIENTES TC on TC.ID_CLIENTE = C.IDCLIENTE

go