use BASEDEDADOS

create trigger TRG_ATUALIZA_PRECO on dbo.PRODUTOS
for update as
if update(PRECO)
begin
	DECLARE @IDHISTORICO int
	DECLARE @PRODUTO varchar(50)
	DECLARE @CATEGORIA varchar(30)
	DECLARE @PRECOANTIGO numeric(10,2)
	DECLARE @PRECONOVO numeric(10,2)
	
	SELECT @IDHISTORICO = IDPRODUTO FROM INSERTED
	SELECT @PRODUTO = NOME FROM INSERTED
	SELECT @CATEGORIA = CATEGORIA FROM INSERTED
	SELECT @PRECOANTIGO = PRECO FROM DELETED
	SELECT @PRECONOVO = PRECO FROM INSERTED
	
	INSERT INTO HISTORICODEPRECO
	(IDHISTORICO, PRODUTO, CATEGORIA, PRECOANTIGO, PRECONOVO)
	VALUES
	(@IDHISTORICO,@PRODUTO,@CATEGORIA,@PRECOANTIGO,@PRECONOVO)
end

go